"""Add contact fields to supplier

Revision ID: c3192097848e
Revises: 9620975b21f8
Create Date: 2026-07-23 23:37:18.751712+00:00
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3192097848e'
down_revision: Union[str, None] = '9620975b21f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suppliers', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('suppliers', sa.Column('phone', sa.String(length=50), nullable=True))
    op.add_column('suppliers', sa.Column('contact_person', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suppliers', 'contact_person')
    op.drop_column('suppliers', 'phone')
    op.drop_column('suppliers', 'email')
    # ### end Alembic commands ###
