"""Add category to product

Revision ID: cf7707d7dfbc
Revises: c3192097848e
Create Date: 2026-07-24 05:56:47.421775+00:00
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf7707d7dfbc'
down_revision: Union[str, None] = 'c3192097848e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('category', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_column('products', 'category')
    # ### end Alembic commands ###
