"""Set nullable SET NULL on product and supplier FKs

Revision ID: 3a7541ee1e6c
Revises: cf7707d7dfbc
Create Date: 2026-07-25 18:50:21.532818+00:00
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a7541ee1e6c'
down_revision: Union[str, None] = 'cf7707d7dfbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('purchase_items', 'product_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('purchase_items_product_id_fkey', 'purchase_items', type_='foreignkey')
    op.create_foreign_key(None, 'purchase_items', 'products', ['product_id'], ['id'], ondelete='SET NULL')
    op.alter_column('purchases', 'supplier_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('purchases_supplier_id_fkey', 'purchases', type_='foreignkey')
    op.create_foreign_key(None, 'purchases', 'suppliers', ['supplier_id'], ['id'], ondelete='SET NULL')
    op.alter_column('sale_items', 'product_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('sale_items_product_id_fkey', 'sale_items', type_='foreignkey')
    op.create_foreign_key(None, 'sale_items', 'products', ['product_id'], ['id'], ondelete='SET NULL')
    op.alter_column('stock_movements', 'product_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('stock_movements_product_id_fkey', 'stock_movements', type_='foreignkey')
    op.create_foreign_key(None, 'stock_movements', 'products', ['product_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stock_movements', type_='foreignkey')
    op.create_foreign_key('stock_movements_product_id_fkey', 'stock_movements', 'products', ['product_id'], ['id'], ondelete='RESTRICT')
    op.alter_column('stock_movements', 'product_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'sale_items', type_='foreignkey')
    op.create_foreign_key('sale_items_product_id_fkey', 'sale_items', 'products', ['product_id'], ['id'], ondelete='RESTRICT')
    op.alter_column('sale_items', 'product_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'purchases', type_='foreignkey')
    op.create_foreign_key('purchases_supplier_id_fkey', 'purchases', 'suppliers', ['supplier_id'], ['id'], ondelete='RESTRICT')
    op.alter_column('purchases', 'supplier_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'purchase_items', type_='foreignkey')
    op.create_foreign_key('purchase_items_product_id_fkey', 'purchase_items', 'products', ['product_id'], ['id'], ondelete='RESTRICT')
    op.alter_column('purchase_items', 'product_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
