"""Remove phone_number from User

Revision ID: 6f1c01ef80e2
Revises: 7aa89e68b4d9
Create Date: 2026-07-28 19:50:27.375699+00:00
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f1c01ef80e2'
down_revision: Union[str, None] = '7aa89e68b4d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
